language: haskell

ghc:
  - 7.8
  - 7.6

before_install:
    - sudo apt-get -qq update
    - sudo apt-get install libjudy-dev libarchive-dev pkg-config libtool autoconf automake make git clang
    - git clone https://github.com/traildb/traildb && cd traildb && mkdir m4 && ./autogen.sh && CC=clang ./configure --prefix=/usr && make && sudo make install

install:
    - cabal install --only-dependencies

script:
    - cabal configure && cabal build

